package com.busience.standard.Dto;

public class EQUIPMENT_INFO_TBL {

	private int id;
	private String EQUIPMENT_BUSINESS_PLACE; // �����(�������̺�)
	private String EQUIPMENT_BUSINESS_PLACE_NAME; // ������(����)
	private String EQUIPMENT_INFO_CODE; // �����ڵ�(�⺻Ű)
	private String EQUIPMENT_INFO_NAME; // �����
	private String EQUIPMENT_INFO_ABR; // ����ȣ��
	private float EQUIPMENT_HEIGHT; // ����(����)
	private float EQUIPMENT_WIDTH; // ����(��)
	private float EQUIPMENT_DEPTH; // ����(����)
	private String EQUIPMENT_SERIAL_NUM; // ����(�ø��� �ѹ�)
	private float EQUIPMENT_WEIGHT; // ����(����)
	private String EQUIPMENT_RECEIVED_D; // ���� ��������
	private String EQUIPMENT_MODEL_YEAR; // ���� ����
	private String EQUIPMENT_MANUFACTURER; // ���۾�ü
	private String EQUIPMENT_STATUS; // �������(�����ڵ�)
	private String EQUIPMENT_STATUS_NAME; // ������¸�(����)
	private String EQUIPMENT_INFO_RMARK; // ���
	private String EQUIPMENT_USE_STATUS; // �������
	private String EQUIPMENT_MODIFY_D; // ��������
	private String EQUIPMENT_MODIFIER; // ������
	private String EQUIPMENT_FilePath; // ���� ����
	private Integer EQUIPMENT_CheckList_Count;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getEQUIPMENT_BUSINESS_PLACE() {
		return EQUIPMENT_BUSINESS_PLACE;
	}
	public void setEQUIPMENT_BUSINESS_PLACE(String eQUIPMENT_BUSINESS_PLACE) {
		EQUIPMENT_BUSINESS_PLACE = eQUIPMENT_BUSINESS_PLACE;
	}
	public String getEQUIPMENT_BUSINESS_PLACE_NAME() {
		return EQUIPMENT_BUSINESS_PLACE_NAME;
	}
	public void setEQUIPMENT_BUSINESS_PLACE_NAME(String eQUIPMENT_BUSINESS_PLACE_NAME) {
		EQUIPMENT_BUSINESS_PLACE_NAME = eQUIPMENT_BUSINESS_PLACE_NAME;
	}
	public String getEQUIPMENT_INFO_CODE() {
		return EQUIPMENT_INFO_CODE;
	}
	public void setEQUIPMENT_INFO_CODE(String eQUIPMENT_INFO_CODE) {
		EQUIPMENT_INFO_CODE = eQUIPMENT_INFO_CODE;
	}
	public String getEQUIPMENT_INFO_NAME() {
		return EQUIPMENT_INFO_NAME;
	}
	public void setEQUIPMENT_INFO_NAME(String eQUIPMENT_INFO_NAME) {
		EQUIPMENT_INFO_NAME = eQUIPMENT_INFO_NAME;
	}
	public String getEQUIPMENT_INFO_ABR() {
		return EQUIPMENT_INFO_ABR;
	}
	public void setEQUIPMENT_INFO_ABR(String eQUIPMENT_INFO_ABR) {
		EQUIPMENT_INFO_ABR = eQUIPMENT_INFO_ABR;
	}
	public float getEQUIPMENT_HEIGHT() {
		return EQUIPMENT_HEIGHT;
	}
	public void setEQUIPMENT_HEIGHT(float eQUIPMENT_HEIGHT) {
		EQUIPMENT_HEIGHT = eQUIPMENT_HEIGHT;
	}
	public float getEQUIPMENT_WIDTH() {
		return EQUIPMENT_WIDTH;
	}
	public void setEQUIPMENT_WIDTH(float eQUIPMENT_WIDTH) {
		EQUIPMENT_WIDTH = eQUIPMENT_WIDTH;
	}
	public float getEQUIPMENT_DEPTH() {
		return EQUIPMENT_DEPTH;
	}
	public void setEQUIPMENT_DEPTH(float eQUIPMENT_DEPTH) {
		EQUIPMENT_DEPTH = eQUIPMENT_DEPTH;
	}
	public String getEQUIPMENT_SERIAL_NUM() {
		return EQUIPMENT_SERIAL_NUM;
	}
	public void setEQUIPMENT_SERIAL_NUM(String eQUIPMENT_SERIAL_NUM) {
		EQUIPMENT_SERIAL_NUM = eQUIPMENT_SERIAL_NUM;
	}
	public float getEQUIPMENT_WEIGHT() {
		return EQUIPMENT_WEIGHT;
	}
	public void setEQUIPMENT_WEIGHT(float eQUIPMENT_WEIGHT) {
		EQUIPMENT_WEIGHT = eQUIPMENT_WEIGHT;
	}
	public String getEQUIPMENT_RECEIVED_D() {
		return EQUIPMENT_RECEIVED_D;
	}
	public void setEQUIPMENT_RECEIVED_D(String eQUIPMENT_RECEIVED_D) {
		EQUIPMENT_RECEIVED_D = eQUIPMENT_RECEIVED_D;
	}
	public String getEQUIPMENT_MODEL_YEAR() {
		return EQUIPMENT_MODEL_YEAR;
	}
	public void setEQUIPMENT_MODEL_YEAR(String eQUIPMENT_MODEL_YEAR) {
		EQUIPMENT_MODEL_YEAR = eQUIPMENT_MODEL_YEAR;
	}
	public String getEQUIPMENT_MANUFACTURER() {
		return EQUIPMENT_MANUFACTURER;
	}
	public void setEQUIPMENT_MANUFACTURER(String eQUIPMENT_MANUFACTURER) {
		EQUIPMENT_MANUFACTURER = eQUIPMENT_MANUFACTURER;
	}
	public String getEQUIPMENT_STATUS() {
		return EQUIPMENT_STATUS;
	}
	public void setEQUIPMENT_STATUS(String eQUIPMENT_STATUS) {
		EQUIPMENT_STATUS = eQUIPMENT_STATUS;
	}
	public String getEQUIPMENT_STATUS_NAME() {
		return EQUIPMENT_STATUS_NAME;
	}
	public void setEQUIPMENT_STATUS_NAME(String eQUIPMENT_STATUS_NAME) {
		EQUIPMENT_STATUS_NAME = eQUIPMENT_STATUS_NAME;
	}
	public String getEQUIPMENT_INFO_RMARK() {
		return EQUIPMENT_INFO_RMARK;
	}
	public void setEQUIPMENT_INFO_RMARK(String eQUIPMENT_INFO_RMARK) {
		EQUIPMENT_INFO_RMARK = eQUIPMENT_INFO_RMARK;
	}
	public String getEQUIPMENT_USE_STATUS() {
		return EQUIPMENT_USE_STATUS;
	}
	public void setEQUIPMENT_USE_STATUS(String eQUIPMENT_USE_STATUS) {
		EQUIPMENT_USE_STATUS = eQUIPMENT_USE_STATUS;
	}
	public String getEQUIPMENT_MODIFY_D() {
		return EQUIPMENT_MODIFY_D;
	}
	public void setEQUIPMENT_MODIFY_D(String eQUIPMENT_MODIFY_D) {
		EQUIPMENT_MODIFY_D = eQUIPMENT_MODIFY_D;
	}
	public String getEQUIPMENT_MODIFIER() {
		return EQUIPMENT_MODIFIER;
	}
	public void setEQUIPMENT_MODIFIER(String eQUIPMENT_MODIFIER) {
		EQUIPMENT_MODIFIER = eQUIPMENT_MODIFIER;
	}
	public String getEQUIPMENT_FilePath() {
		return EQUIPMENT_FilePath;
	}
	public void setEQUIPMENT_FilePath(String eQUIPMENT_FilePath) {
		EQUIPMENT_FilePath = eQUIPMENT_FilePath;
	}
	public Integer getEQUIPMENT_CheckList_Count() {
		return EQUIPMENT_CheckList_Count;
	}
	public void setEQUIPMENT_CheckList_Count(Integer eQUIPMENT_CheckList_Count) {
		EQUIPMENT_CheckList_Count = eQUIPMENT_CheckList_Count;
	}
	@Override
	public String toString() {
		return "EQUIPMENT_INFO_TBL [id=" + id + ", EQUIPMENT_BUSINESS_PLACE=" + EQUIPMENT_BUSINESS_PLACE
				+ ", EQUIPMENT_BUSINESS_PLACE_NAME=" + EQUIPMENT_BUSINESS_PLACE_NAME + ", EQUIPMENT_INFO_CODE="
				+ EQUIPMENT_INFO_CODE + ", EQUIPMENT_INFO_NAME=" + EQUIPMENT_INFO_NAME + ", EQUIPMENT_INFO_ABR="
				+ EQUIPMENT_INFO_ABR + ", EQUIPMENT_HEIGHT=" + EQUIPMENT_HEIGHT + ", EQUIPMENT_WIDTH=" + EQUIPMENT_WIDTH
				+ ", EQUIPMENT_DEPTH=" + EQUIPMENT_DEPTH + ", EQUIPMENT_SERIAL_NUM=" + EQUIPMENT_SERIAL_NUM
				+ ", EQUIPMENT_WEIGHT=" + EQUIPMENT_WEIGHT + ", EQUIPMENT_RECEIVED_D=" + EQUIPMENT_RECEIVED_D
				+ ", EQUIPMENT_MODEL_YEAR=" + EQUIPMENT_MODEL_YEAR + ", EQUIPMENT_MANUFACTURER="
				+ EQUIPMENT_MANUFACTURER + ", EQUIPMENT_STATUS=" + EQUIPMENT_STATUS + ", EQUIPMENT_STATUS_NAME="
				+ EQUIPMENT_STATUS_NAME + ", EQUIPMENT_INFO_RMARK=" + EQUIPMENT_INFO_RMARK + ", EQUIPMENT_USE_STATUS="
				+ EQUIPMENT_USE_STATUS + ", EQUIPMENT_MODIFY_D=" + EQUIPMENT_MODIFY_D + ", EQUIPMENT_MODIFIER="
				+ EQUIPMENT_MODIFIER + ", EQUIPMENT_FilePath=" + EQUIPMENT_FilePath + ", EQUIPMENT_CheckList_Count="
				+ EQUIPMENT_CheckList_Count + "]";
	}

}
