package com.busience.standard.Dto;

public class PRODUCT_INFO_TBL {
	int id;
	private String PRODUCT_BUSINESS_PLACE; // 사업장코드(세부테이블)
	private String PRODUCT_BUSINESS_PLACE_NAME; // 사업장명(세부테이블)
	private String PRODUCT_ITEM_CODE; // 품목코드(기본키)
	private String PRODUCT_OLD_ITEM_CODE; // 구품목코드
	private String PRODUCT_ITEM_NAME; // 품명
	private String PRODUCT_INFO_STND_1; // 규격1
	private String PRODUCT_INFO_STND_2; // 규격2
	private int PRODUCT_UNIT_PRICE;
	private String PRODUCT_UNIT; // 단위코드(세부코드)
	private String PRODUCT_UNIT_NAME; // 단위명(세부코드)
	private String PRODUCT_MATERIAL; // 재질코드(세부코드)
	private String PRODUCT_MATERIAL_NAME; // 재질명(세부코드)
	private String PRODUCT_MTRL_CLSFC; // 자재분류코드 (세부코드)
	private String PRODUCT_MTRL_CLSFC_NAME; // 자재분류명 (세부코드)
	private String PRODUCT_ITEM_CLSFC_1; // 품목분류코드1 (세부코드)
	private String PRODUCT_ITEM_CLSFC_1_NAME; // 품목분류명1 (세부코드)
	private String PRODUCT_ITEM_CLSFC_2; // 품목분류코드2 (세부코드)
	private String PRODUCT_ITEM_CLSFC_2_NAME; // 품목분류명2 (세부코드)
	private String PRODUCT_SUBSID_MATL_MGMT; // 부자재관리
	private String PRODUCT_ITEM_STTS; // 품목상태코드 (세부코드)
	private String PRODUCT_ITEM_STTS_NAME; // 품목상태명 (세부코드)
	private String PRODUCT_BASIC_WAREHOUSE; // 기본창고코드 (세부코드)
	private String PRODUCT_BASIC_WAREHOUSE_NAME; // 기본창고명 (세부코드)
	private String PRODUCT_SAVE_AREA; // 보관구역
	private String PRODUCT_SAVE_AREA_NAME; // 보관구역명
	private int PRODUCT_SFTY_STOCK; // 안전재고
	private String PRODUCT_BUYER; // 구매담당자
	private String PRODUCT_WRHSN_INSPC; // 입고검사
	private String PRODUCT_USE_STATUS; // 사용유무
	private String PRODUCT_MODIFY_D; // 수정일자
	private String PRODUCT_MODIFIER; // 수정자
	private boolean BOM_Registered; // Bom 등록 여부
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getPRODUCT_BUSINESS_PLACE() {
		return PRODUCT_BUSINESS_PLACE;
	}
	public void setPRODUCT_BUSINESS_PLACE(String pRODUCT_BUSINESS_PLACE) {
		PRODUCT_BUSINESS_PLACE = pRODUCT_BUSINESS_PLACE;
	}
	public String getPRODUCT_BUSINESS_PLACE_NAME() {
		return PRODUCT_BUSINESS_PLACE_NAME;
	}
	public void setPRODUCT_BUSINESS_PLACE_NAME(String pRODUCT_BUSINESS_PLACE_NAME) {
		PRODUCT_BUSINESS_PLACE_NAME = pRODUCT_BUSINESS_PLACE_NAME;
	}
	public String getPRODUCT_ITEM_CODE() {
		return PRODUCT_ITEM_CODE;
	}
	public void setPRODUCT_ITEM_CODE(String pRODUCT_ITEM_CODE) {
		PRODUCT_ITEM_CODE = pRODUCT_ITEM_CODE;
	}
	public String getPRODUCT_OLD_ITEM_CODE() {
		return PRODUCT_OLD_ITEM_CODE;
	}
	public void setPRODUCT_OLD_ITEM_CODE(String pRODUCT_OLD_ITEM_CODE) {
		PRODUCT_OLD_ITEM_CODE = pRODUCT_OLD_ITEM_CODE;
	}
	public String getPRODUCT_ITEM_NAME() {
		return PRODUCT_ITEM_NAME;
	}
	public void setPRODUCT_ITEM_NAME(String pRODUCT_ITEM_NAME) {
		PRODUCT_ITEM_NAME = pRODUCT_ITEM_NAME;
	}
	public String getPRODUCT_INFO_STND_1() {
		return PRODUCT_INFO_STND_1;
	}
	public void setPRODUCT_INFO_STND_1(String pRODUCT_INFO_STND_1) {
		PRODUCT_INFO_STND_1 = pRODUCT_INFO_STND_1;
	}
	public String getPRODUCT_INFO_STND_2() {
		return PRODUCT_INFO_STND_2;
	}
	public void setPRODUCT_INFO_STND_2(String pRODUCT_INFO_STND_2) {
		PRODUCT_INFO_STND_2 = pRODUCT_INFO_STND_2;
	}
	public int getPRODUCT_UNIT_PRICE() {
		return PRODUCT_UNIT_PRICE;
	}
	public void setPRODUCT_UNIT_PRICE(int pRODUCT_UNIT_PRICE) {
		PRODUCT_UNIT_PRICE = pRODUCT_UNIT_PRICE;
	}
	public String getPRODUCT_UNIT() {
		return PRODUCT_UNIT;
	}
	public void setPRODUCT_UNIT(String pRODUCT_UNIT) {
		PRODUCT_UNIT = pRODUCT_UNIT;
	}
	public String getPRODUCT_UNIT_NAME() {
		return PRODUCT_UNIT_NAME;
	}
	public void setPRODUCT_UNIT_NAME(String pRODUCT_UNIT_NAME) {
		PRODUCT_UNIT_NAME = pRODUCT_UNIT_NAME;
	}
	public String getPRODUCT_MATERIAL() {
		return PRODUCT_MATERIAL;
	}
	public void setPRODUCT_MATERIAL(String pRODUCT_MATERIAL) {
		PRODUCT_MATERIAL = pRODUCT_MATERIAL;
	}
	public String getPRODUCT_MATERIAL_NAME() {
		return PRODUCT_MATERIAL_NAME;
	}
	public void setPRODUCT_MATERIAL_NAME(String pRODUCT_MATERIAL_NAME) {
		PRODUCT_MATERIAL_NAME = pRODUCT_MATERIAL_NAME;
	}
	public String getPRODUCT_MTRL_CLSFC() {
		return PRODUCT_MTRL_CLSFC;
	}
	public void setPRODUCT_MTRL_CLSFC(String pRODUCT_MTRL_CLSFC) {
		PRODUCT_MTRL_CLSFC = pRODUCT_MTRL_CLSFC;
	}
	public String getPRODUCT_MTRL_CLSFC_NAME() {
		return PRODUCT_MTRL_CLSFC_NAME;
	}
	public void setPRODUCT_MTRL_CLSFC_NAME(String pRODUCT_MTRL_CLSFC_NAME) {
		PRODUCT_MTRL_CLSFC_NAME = pRODUCT_MTRL_CLSFC_NAME;
	}
	public String getPRODUCT_ITEM_CLSFC_1() {
		return PRODUCT_ITEM_CLSFC_1;
	}
	public void setPRODUCT_ITEM_CLSFC_1(String pRODUCT_ITEM_CLSFC_1) {
		PRODUCT_ITEM_CLSFC_1 = pRODUCT_ITEM_CLSFC_1;
	}
	public String getPRODUCT_ITEM_CLSFC_1_NAME() {
		return PRODUCT_ITEM_CLSFC_1_NAME;
	}
	public void setPRODUCT_ITEM_CLSFC_1_NAME(String pRODUCT_ITEM_CLSFC_1_NAME) {
		PRODUCT_ITEM_CLSFC_1_NAME = pRODUCT_ITEM_CLSFC_1_NAME;
	}
	public String getPRODUCT_ITEM_CLSFC_2() {
		return PRODUCT_ITEM_CLSFC_2;
	}
	public void setPRODUCT_ITEM_CLSFC_2(String pRODUCT_ITEM_CLSFC_2) {
		PRODUCT_ITEM_CLSFC_2 = pRODUCT_ITEM_CLSFC_2;
	}
	public String getPRODUCT_ITEM_CLSFC_2_NAME() {
		return PRODUCT_ITEM_CLSFC_2_NAME;
	}
	public void setPRODUCT_ITEM_CLSFC_2_NAME(String pRODUCT_ITEM_CLSFC_2_NAME) {
		PRODUCT_ITEM_CLSFC_2_NAME = pRODUCT_ITEM_CLSFC_2_NAME;
	}
	public String getPRODUCT_SUBSID_MATL_MGMT() {
		return PRODUCT_SUBSID_MATL_MGMT;
	}
	public void setPRODUCT_SUBSID_MATL_MGMT(String pRODUCT_SUBSID_MATL_MGMT) {
		PRODUCT_SUBSID_MATL_MGMT = pRODUCT_SUBSID_MATL_MGMT;
	}
	public String getPRODUCT_ITEM_STTS() {
		return PRODUCT_ITEM_STTS;
	}
	public void setPRODUCT_ITEM_STTS(String pRODUCT_ITEM_STTS) {
		PRODUCT_ITEM_STTS = pRODUCT_ITEM_STTS;
	}
	public String getPRODUCT_ITEM_STTS_NAME() {
		return PRODUCT_ITEM_STTS_NAME;
	}
	public void setPRODUCT_ITEM_STTS_NAME(String pRODUCT_ITEM_STTS_NAME) {
		PRODUCT_ITEM_STTS_NAME = pRODUCT_ITEM_STTS_NAME;
	}
	public String getPRODUCT_BASIC_WAREHOUSE() {
		return PRODUCT_BASIC_WAREHOUSE;
	}
	public void setPRODUCT_BASIC_WAREHOUSE(String pRODUCT_BASIC_WAREHOUSE) {
		PRODUCT_BASIC_WAREHOUSE = pRODUCT_BASIC_WAREHOUSE;
	}
	public String getPRODUCT_BASIC_WAREHOUSE_NAME() {
		return PRODUCT_BASIC_WAREHOUSE_NAME;
	}
	public void setPRODUCT_BASIC_WAREHOUSE_NAME(String pRODUCT_BASIC_WAREHOUSE_NAME) {
		PRODUCT_BASIC_WAREHOUSE_NAME = pRODUCT_BASIC_WAREHOUSE_NAME;
	}
	public String getPRODUCT_SAVE_AREA() {
		return PRODUCT_SAVE_AREA;
	}
	public void setPRODUCT_SAVE_AREA(String pRODUCT_SAVE_AREA) {
		PRODUCT_SAVE_AREA = pRODUCT_SAVE_AREA;
	}
	public String getPRODUCT_SAVE_AREA_NAME() {
		return PRODUCT_SAVE_AREA_NAME;
	}
	public void setPRODUCT_SAVE_AREA_NAME(String pRODUCT_SAVE_AREA_NAME) {
		PRODUCT_SAVE_AREA_NAME = pRODUCT_SAVE_AREA_NAME;
	}
	public int getPRODUCT_SFTY_STOCK() {
		return PRODUCT_SFTY_STOCK;
	}
	public void setPRODUCT_SFTY_STOCK(int pRODUCT_SFTY_STOCK) {
		PRODUCT_SFTY_STOCK = pRODUCT_SFTY_STOCK;
	}
	public String getPRODUCT_BUYER() {
		return PRODUCT_BUYER;
	}
	public void setPRODUCT_BUYER(String pRODUCT_BUYER) {
		PRODUCT_BUYER = pRODUCT_BUYER;
	}
	public String getPRODUCT_WRHSN_INSPC() {
		return PRODUCT_WRHSN_INSPC;
	}
	public void setPRODUCT_WRHSN_INSPC(String pRODUCT_WRHSN_INSPC) {
		PRODUCT_WRHSN_INSPC = pRODUCT_WRHSN_INSPC;
	}
	public String getPRODUCT_USE_STATUS() {
		return PRODUCT_USE_STATUS;
	}
	public void setPRODUCT_USE_STATUS(String pRODUCT_USE_STATUS) {
		PRODUCT_USE_STATUS = pRODUCT_USE_STATUS;
	}
	public String getPRODUCT_MODIFY_D() {
		return PRODUCT_MODIFY_D;
	}
	public void setPRODUCT_MODIFY_D(String pRODUCT_MODIFY_D) {
		PRODUCT_MODIFY_D = pRODUCT_MODIFY_D;
	}
	public String getPRODUCT_MODIFIER() {
		return PRODUCT_MODIFIER;
	}
	public void setPRODUCT_MODIFIER(String pRODUCT_MODIFIER) {
		PRODUCT_MODIFIER = pRODUCT_MODIFIER;
	}
	public boolean isBOM_Registered() {
		return BOM_Registered;
	}
	public void setBOM_Registered(boolean bOM_Registered) {
		BOM_Registered = bOM_Registered;
	}
	@Override
	public String toString() {
		return "PRODUCT_INFO_TBL [id=" + id + ", PRODUCT_BUSINESS_PLACE=" + PRODUCT_BUSINESS_PLACE
				+ ", PRODUCT_BUSINESS_PLACE_NAME=" + PRODUCT_BUSINESS_PLACE_NAME + ", PRODUCT_ITEM_CODE="
				+ PRODUCT_ITEM_CODE + ", PRODUCT_OLD_ITEM_CODE=" + PRODUCT_OLD_ITEM_CODE + ", PRODUCT_ITEM_NAME="
				+ PRODUCT_ITEM_NAME + ", PRODUCT_INFO_STND_1=" + PRODUCT_INFO_STND_1 + ", PRODUCT_INFO_STND_2="
				+ PRODUCT_INFO_STND_2 + ", PRODUCT_UNIT_PRICE=" + PRODUCT_UNIT_PRICE + ", PRODUCT_UNIT=" + PRODUCT_UNIT
				+ ", PRODUCT_UNIT_NAME=" + PRODUCT_UNIT_NAME + ", PRODUCT_MATERIAL=" + PRODUCT_MATERIAL
				+ ", PRODUCT_MATERIAL_NAME=" + PRODUCT_MATERIAL_NAME + ", PRODUCT_MTRL_CLSFC=" + PRODUCT_MTRL_CLSFC
				+ ", PRODUCT_MTRL_CLSFC_NAME=" + PRODUCT_MTRL_CLSFC_NAME + ", PRODUCT_ITEM_CLSFC_1="
				+ PRODUCT_ITEM_CLSFC_1 + ", PRODUCT_ITEM_CLSFC_1_NAME=" + PRODUCT_ITEM_CLSFC_1_NAME
				+ ", PRODUCT_ITEM_CLSFC_2=" + PRODUCT_ITEM_CLSFC_2 + ", PRODUCT_ITEM_CLSFC_2_NAME="
				+ PRODUCT_ITEM_CLSFC_2_NAME + ", PRODUCT_SUBSID_MATL_MGMT=" + PRODUCT_SUBSID_MATL_MGMT
				+ ", PRODUCT_ITEM_STTS=" + PRODUCT_ITEM_STTS + ", PRODUCT_ITEM_STTS_NAME=" + PRODUCT_ITEM_STTS_NAME
				+ ", PRODUCT_BASIC_WAREHOUSE=" + PRODUCT_BASIC_WAREHOUSE + ", PRODUCT_BASIC_WAREHOUSE_NAME="
				+ PRODUCT_BASIC_WAREHOUSE_NAME + ", PRODUCT_SAVE_AREA=" + PRODUCT_SAVE_AREA
				+ ", PRODUCT_SAVE_AREA_NAME=" + PRODUCT_SAVE_AREA_NAME + ", PRODUCT_SFTY_STOCK=" + PRODUCT_SFTY_STOCK
				+ ", PRODUCT_BUYER=" + PRODUCT_BUYER + ", PRODUCT_WRHSN_INSPC=" + PRODUCT_WRHSN_INSPC
				+ ", PRODUCT_USE_STATUS=" + PRODUCT_USE_STATUS + ", PRODUCT_MODIFY_D=" + PRODUCT_MODIFY_D
				+ ", PRODUCT_MODIFIER=" + PRODUCT_MODIFIER + ", BOM_Registered=" + BOM_Registered + "]";
	}
	
	
}
