package com.busience.system.Dto;

public class MENU_MGMT_TBL {
	String MENU_USER_CODE,MENU_PROGRAM_CODE,MENU_READ_USE_STATUS,MENU_WRITE_USE_STATUS,MENU_DEL_USE_STATUS,MENU_MGMT_USE_STATU,MENU_PROGRAM_NAME;

	public String getMENU_USER_CODE() {
		return MENU_USER_CODE;
	}

	public void setMENU_USER_CODE(String mENU_USER_CODE) {
		MENU_USER_CODE = mENU_USER_CODE;
	}

	public String getMENU_PROGRAM_CODE() {
		return MENU_PROGRAM_CODE;
	}

	public void setMENU_PROGRAM_CODE(String mENU_PROGRAM_CODE) {
		MENU_PROGRAM_CODE = mENU_PROGRAM_CODE;
	}

	public String getMENU_READ_USE_STATUS() {
		return MENU_READ_USE_STATUS;
	}

	public void setMENU_READ_USE_STATUS(String mENU_READ_USE_STATUS) {
		MENU_READ_USE_STATUS = mENU_READ_USE_STATUS;
	}

	public String getMENU_WRITE_USE_STATUS() {
		return MENU_WRITE_USE_STATUS;
	}

	public void setMENU_WRITE_USE_STATUS(String mENU_WRITE_USE_STATUS) {
		MENU_WRITE_USE_STATUS = mENU_WRITE_USE_STATUS;
	}

	public String getMENU_DEL_USE_STATUS() {
		return MENU_DEL_USE_STATUS;
	}

	public void setMENU_DEL_USE_STATUS(String mENU_DEL_USE_STATUS) {
		MENU_DEL_USE_STATUS = mENU_DEL_USE_STATUS;
	}

	public String getMENU_MGMT_USE_STATU() {
		return MENU_MGMT_USE_STATU;
	}

	public void setMENU_MGMT_USE_STATU(String mENU_MGMT_USE_STATU) {
		MENU_MGMT_USE_STATU = mENU_MGMT_USE_STATU;
	}

	public String getMENU_PROGRAM_NAME() {
		return MENU_PROGRAM_NAME;
	}

	public void setMENU_PROGRAM_NAME(String mENU_PROGRAM_NAME) {
		MENU_PROGRAM_NAME = mENU_PROGRAM_NAME;
	}

	@Override
	public String toString() {
		return "MENU_MGMT_TBL [MENU_USER_CODE=" + MENU_USER_CODE + ", MENU_PROGRAM_CODE=" + MENU_PROGRAM_CODE
				+ ", MENU_READ_USE_STATUS=" + MENU_READ_USE_STATUS + ", MENU_WRITE_USE_STATUS=" + MENU_WRITE_USE_STATUS
				+ ", MENU_DEL_USE_STATUS=" + MENU_DEL_USE_STATUS + ", MENU_MGMT_USE_STATU=" + MENU_MGMT_USE_STATU
				+ ", MENU_PROGRAM_NAME=" + MENU_PROGRAM_NAME + "]";
	}

	public MENU_MGMT_TBL(String mENU_USER_CODE, String mENU_PROGRAM_CODE, String mENU_READ_USE_STATUS,
			String mENU_WRITE_USE_STATUS, String mENU_DEL_USE_STATUS, String mENU_MGMT_USE_STATU,
			String mENU_PROGRAM_NAME) {
		super();
		MENU_USER_CODE = mENU_USER_CODE;
		MENU_PROGRAM_CODE = mENU_PROGRAM_CODE;
		MENU_READ_USE_STATUS = mENU_READ_USE_STATUS;
		MENU_WRITE_USE_STATUS = mENU_WRITE_USE_STATUS;
		MENU_DEL_USE_STATUS = mENU_DEL_USE_STATUS;
		MENU_MGMT_USE_STATU = mENU_MGMT_USE_STATU;
		MENU_PROGRAM_NAME = mENU_PROGRAM_NAME;
	}

	public MENU_MGMT_TBL() {
		super();
	}
}
