package com.busience.system.Dto;

public class RIGHTS_MGMT_TBL {
	String RIGHTS_USER_TYPE, RIGHTS_PROGRAM_CODE, RIGHTS_MGMT_USE_STATUS;

	String CHILD_TBL_NO, NEW_TBL_CODE, CHILD_TBL_NUM, CHILD_TBL_TYPE, CHILD_TBL_RMARK;

	public RIGHTS_MGMT_TBL(String rIGHTS_USER_TYPE, String rIGHTS_PROGRAM_CODE, String rIGHTS_MGMT_USE_STATUS,
			String cHILD_TBL_NO, String nEW_TBL_CODE, String cHILD_TBL_NUM, String cHILD_TBL_TYPE,
			String cHILD_TBL_RMARK) {
		super();
		RIGHTS_USER_TYPE = rIGHTS_USER_TYPE;
		RIGHTS_PROGRAM_CODE = rIGHTS_PROGRAM_CODE;
		RIGHTS_MGMT_USE_STATUS = rIGHTS_MGMT_USE_STATUS;
		CHILD_TBL_NO = cHILD_TBL_NO;
		NEW_TBL_CODE = nEW_TBL_CODE;
		CHILD_TBL_NUM = cHILD_TBL_NUM;
		CHILD_TBL_TYPE = cHILD_TBL_TYPE;
		CHILD_TBL_RMARK = cHILD_TBL_RMARK;
	}

	public RIGHTS_MGMT_TBL() {
		super();
	}

	public String getCHILD_TBL_NO() {
		return CHILD_TBL_NO;
	}

	public void setCHILD_TBL_NO(String cHILD_TBL_NO) {
		CHILD_TBL_NO = cHILD_TBL_NO;
	}

	public String getRIGHTS_USER_TYPE() {
		return RIGHTS_USER_TYPE;
	}

	public void setRIGHTS_USER_TYPE(String rIGHTS_USER_TYPE) {
		RIGHTS_USER_TYPE = rIGHTS_USER_TYPE;
	}

	public String getRIGHTS_PROGRAM_CODE() {
		return RIGHTS_PROGRAM_CODE;
	}

	public void setRIGHTS_PROGRAM_CODE(String rIGHTS_PROGRAM_CODE) {
		RIGHTS_PROGRAM_CODE = rIGHTS_PROGRAM_CODE;
	}

	public String getRIGHTS_MGMT_USE_STATUS() {
		return RIGHTS_MGMT_USE_STATUS;
	}

	public void setRIGHTS_MGMT_USE_STATUS(String rIGHTS_MGMT_USE_STATUS) {
		RIGHTS_MGMT_USE_STATUS = rIGHTS_MGMT_USE_STATUS;
	}

	public String getNEW_TBL_CODE() {
		return NEW_TBL_CODE;
	}

	public void setNEW_TBL_CODE(String nEW_TBL_CODE) {
		NEW_TBL_CODE = nEW_TBL_CODE;
	}

	public String getCHILD_TBL_NUM() {
		return CHILD_TBL_NUM;
	}

	public void setCHILD_TBL_NUM(String cHILD_TBL_NUM) {
		CHILD_TBL_NUM = cHILD_TBL_NUM;
	}

	public String getCHILD_TBL_TYPE() {
		return CHILD_TBL_TYPE;
	}

	public void setCHILD_TBL_TYPE(String cHILD_TBL_TYPE) {
		CHILD_TBL_TYPE = cHILD_TBL_TYPE;
	}

	public String getCHILD_TBL_RMARK() {
		return CHILD_TBL_RMARK;
	}

	public void setCHILD_TBL_RMARK(String cHILD_TBL_RMARK) {
		CHILD_TBL_RMARK = cHILD_TBL_RMARK;
	}

	@Override
	public String toString() {
		return "RIGHTS_MGMT_TBL [RIGHTS_USER_TYPE=" + RIGHTS_USER_TYPE + ", RIGHTS_PROGRAM_CODE=" + RIGHTS_PROGRAM_CODE
				+ ", RIGHTS_MGMT_USE_STATUS=" + RIGHTS_MGMT_USE_STATUS + ", CHILD_TBL_NO=" + CHILD_TBL_NO
				+ ", NEW_TBL_CODE=" + NEW_TBL_CODE + ", CHILD_TBL_NUM=" + CHILD_TBL_NUM + ", CHILD_TBL_TYPE="
				+ CHILD_TBL_TYPE + ", CHILD_TBL_RMARK=" + CHILD_TBL_RMARK + "]";
	}

}
